### ISSUE TITLE
Search should open the tree and shows the count of matches

### ISSUE THREAD

**Issue by iranapex** [mt-ag/apex-fancytree-plugin#7]
the tree does not show the count of matched search string and does not open the tree to that node.

**Comment by mt-ag** [comment]
Hey,
does it show the count of matches if you expand all nodes? It might just not find any nodes because the tree uses Lazy Loading. The tree can't find any nodes that have not been loaded yet. If you want, you could call the "expand all" function to load all nodes and then hide them immediately by calling the "collapse all" function. This makes sure that all nodes are loaded, but it could take some time to completely load this tree if you have a massive amount of nodes in the tree.
To get the tree to open up to the found nodes, you have to add a little bit of code. On line 258, add the following:
`filter: {
                                        autoExpand: true
                                    },`
If you want to customise the filter/search functionality a bit more, have a look at [this link](https://github.com/mar10/fancytree/wiki/ExtFilter).

**Comment by iranapex** [comment]
Thank you
