### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by orabin** [mt-ag/apex-fancytree-plugin#8]
I could not use your plugin.
Can I further describe how to bind variables to a query? Or get access to export your test application?

Thank you.

**Comment by xCite1986** [comment]
i'm also interested in the whole app-export to look into how to handle the the page items.

could you please upload them as example?

**Comment by mt-ag** [comment]
Hey,

sorry for the late reply. Here is the application
[f140 (1).zip](https://github.com/mt-ag/apex-fancytree-plugin/files/1498633/f140.1.zip)
Just make sure that the EMP table is present since it is not included in the export as far as I know. You might have to import the plug-in as well, so double check if the plug-in is present in the shared components :)

**Comment by xCite1986** [comment]
great, thanks 👍
